### ISSUE TITLE
Dimension lines problems

### ISSUE THREAD

**Issue by itsanov** [xibyte/jsketcher#106]
Dimension lines do not zoom together with model.
Dimension scale not working.
If dimension is selected and backspace is pressed while changing "Dimension scale" - dimension line is deleted.
Dimension lines are not exported together with model.

**Comment by mmiscool** [comment]
Are you running locally from source or using web-cad.org?

**Comment by itsanov** [comment]
Locally!
Cloned the "master" brunch of repository.
npm install
npm start

**Comment by mmiscool** [comment]
Is this still an issue for you? 
If so could you record a screen video showing the problem and post here? Not sure I understand what you are referring to with the dimension scale.

**Comment by mmiscool** [comment]
Closing old issue. Additional information not provided or issue is no longer present.
