### ISSUE TITLE
can't figure out how to revolve

### ISSUE THREAD

**Issue by dominictarr** [xibyte/jsketcher#111]
I managed to use extrude and loft, but I can't figure out how to make revolve work. I tried to make a torus. I created a plane and drew a circle on it. I could see that I needed to select two things. I clicked on my circle and it seemed to take it, but then for axis I tried to click a datum pointer that was parallel to the face of the circle... but it wouldn't fill the "axis" slot.

then I tried drawing another circle, on a perpendicular plane, this did select as the "axis" but nothing happened.

I don't know what I'm doing wrong, the software looks really good! I can't figure out how it works.

**Comment by mmiscool** [comment]
In the sketch you must create a construction line to use as the center line of the revolve. 

You can select a regular line or a construction line to be the axis 
![revolve](https://user-images.githubusercontent.com/6439772/87254225-f7140900-c44e-11ea-92b1-1d25155aaaa2.gif)

**Comment by mmiscool** [comment]
Example making a sketch with a construction line in it. 
![revolve 2](https://user-images.githubusercontent.com/6439772/87254421-88d04600-c450-11ea-8dc0-8be8eb99d49f.gif)

**Comment by mmiscool** [comment]
No further activity on this issue and demonstrations were provided. Closing.
