### ISSUE TITLE
Chamfer

### ISSUE THREAD

**Issue by probonopd** [xibyte/jsketcher#124]
It would be nice if the Fillet button could become a Fillet/Chamfer button with the option to select whether you want a Fillet or a Chamfer:

![image](https://user-images.githubusercontent.com/2480569/103451707-86e09480-4cc7-11eb-9703-5c7607b9b7ff.png)

**Comment by mmiscool** [comment]
The API to support this implemented but not available on the UI yet. Expect to see this as a feature at some point in the future.

**Comment by mmiscool** [comment]
Implemented in the mdf branch.
