### ISSUE TITLE
Can you provide the import function of SolidWorks model? I can pay for it

### ISSUE THREAD

**Issue by WREQI** [xibyte/jsketcher#127]
Can you provide the import function of SolidWorks model? I can pay for it

**Comment by mmiscool** [comment]
Hello,
We do have import capability from STEP file. All major cad software packages support step file export as this is the preferred interchange format. Importing directly from native solids works would require a large amount of effort and replicating all of the features that solid edge supports to properly import and interpreter the part history. 
Would be happy to talk and discuss your use case and see if we can help but a fully blown solid works import capability is not within the capabilities.

**Comment by WREQI** [comment]
How can I contact you quickly

**Comment by WREQI** [comment]
Discord has expired

**Comment by WREQI** [comment]
I can't reach you on the website

**Comment by WREQI** [comment]
Can you give me your phone number

**Comment by mmiscool** [comment]
I replied to your email. You might have to check your spam folder.
