### ISSUE TITLE
Feature request: Make fillet command in sketcher work by selecting 2 lines if they intersect at a point

### ISSUE THREAD

**Issue by mmiscool** [xibyte/jsketcher#13]
In other cad programs it is common to select 2 lines that are to be filleted. The command would have to infer the point by looking for the point at which the 2 lines intersect.

**Comment by mmiscool** [comment]
Also make it so that selection of point can happen prior to clicking command.

**Comment by xibyte** [comment]
implemented the second comment. now fillet is cerated immediately if there is selection  prior to clicking command.

**Comment by mmiscool** [comment]
This feature is working. Thanks
