### ISSUE TITLE
Is it impossible to import a sketch from SVG/DWG etc? 

### ISSUE THREAD

**Issue by nikkwong** [xibyte/jsketcher#138]
I have an external drawing that I'd like to bring into this program. Is that possible? Also curious if the project is alive, it looks great! Thanks

**Comment by mmiscool** [comment]
Hello, 
Project is alive and looking for funding to be able to accelerate development. 

DXF and SVG are not currently available as import formats however step file support was recently added. 
I am marking this as an enhancement.

**Comment by mmiscool** [comment]
See this issue also. Seems to be duplicate. 
https://github.com/xibyte/jsketcher/issues/108
https://github.com/xibyte/jsketcher/issues/109

**Comment by mmiscool** [comment]
See https://github.com/xibyte/jsketcher/issues/67 for first cut on DXF import functionality and screen shot showing how to import in to the 2D sketcher.
