### ISSUE TITLE
sketch cannot be extruded on Safari

### ISSUE THREAD

**Issue by AoyuW** [xibyte/jsketcher#140]
When I want to extrude the sketch on Safari, it says 'internal error processing operation, check the log', but on Chrome, no such error, why?

**Comment by mmiscool** [comment]
Right now we are only officially testing on chromium based browsers. 
I would tend to think it might be some thing with the web assembly implementation. 

I checked in chrome, edge and brave recently. No problems reported. I believe it is also fully functional in firefox.

**Comment by mmiscool** [comment]
Closing as no additional feedback provided by issue originator.
