### ISSUE TITLE
The constraint has not been updated for a year, when will the constraint solving code be updated?

### ISSUE THREAD

**Issue by WREQI** [xibyte/jsketcher#142]
The constraint has not been updated for a year, when will the constraint solving code be updated?

**Comment by mmiscool** [comment]
Right now we only have one developer working on this project on an intermittent basis. We are currently looking for funding to have them work on it full time but have not found any deep pockets willing to contribute yet. Without stable forms of funding it is difficult to plan and prioritize development on a timeline.
