### ISSUE TITLE
How to use opencascade.js' wasm file in the vue2 architecture？

### ISSUE THREAD

**Issue by YingjuHan** [xibyte/jsketcher#143]
I want to build a web cad using the vue2 architecture.

**Comment by mmiscool** [comment]
I would suggest consulting the documentation and examples in the repo for the opencascade.js project.

**Comment by YingjuHan** [comment]
This problem is about to be resolved, because the two architectures are different, there may be problems in the future, please allow me to ask questions under your project, thank you.

**Comment by YingjuHan** [comment]
This problem is about to be resolved, because the two architectures are different, there may be problems in the future, please allow me to ask questions under your project, thank you.

**Comment by mmiscool** [comment]
I think you would have better luck here. https://github.com/donalffons/opencascade.js/
We only recently started using the opencascade.js
