### ISSUE TITLE
Using num run build and had a problem using it

### ISSUE THREAD

**Issue by YingjuHan** [xibyte/jsketcher#145]
I had an error using num run build and had a problem using it: Uncaught (in promise) TypeError: Failed to execute'compile' on'WebAssembly': Incorrect response MIME type. Expected'application/wasm'.

**Comment by mmiscool** [comment]
If you are using a static build and tossing it on to a generic http server you must make sure that the mime type is added.
See https://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types
https://www.nginx.com/resources/wiki/start/topics/examples/full/
