### ISSUE TITLE
How to add a new layer

### ISSUE THREAD

**Issue by mukral** [xibyte/jsketcher#147]
Hi,

I worked on your page http://web-cad.org/sketcher.html
There I've seen that it is possible to work with sketch layers or construction layers. One layer is given if you start a new sketch. So this would be my sketch layer. But I also need a construction layer and don't find a button to add a one. Could you please give me a hint?

Thanks Markus 

Sorry, I don't want to bother with my newby question so I totally understand if you ignore it...

**Comment by mmiscool** [comment]
Sorry about the late response. 

You can see the list of individual pieces of geometry on the left hand side. They are marked as S by default but can be toggled to C for construction by clicking the letter.
![image](https://user-images.githubusercontent.com/6439772/170858234-9c92e21d-048d-4bb2-adb6-a62c6f5c33a9.png)

![image](https://user-images.githubusercontent.com/6439772/170858283-48a56c0f-fafd-41d2-80db-c0b12ab2d23d.png)
