### ISSUE TITLE
FCStd?

### ISSUE THREAD

**Issue by samuk** [xibyte/jsketcher#160]
Unclear if this is a dead project?

The idea of a [WebUI for FreeCAD came up here](https://forum.freecad.org/viewtopic.php?p=595443&sid=0cbfaf3d2ae44ce2bb725d71a39618f2#p595443) would doing that work be of interest to current or new developers ?

**Comment by mmiscool** [comment]
Hello. I sent you a private message on the free cad forums.

**Comment by mmiscool** [comment]
This feature has now been added.
![image](https://user-images.githubusercontent.com/6439772/181700015-d6d576b1-c8ce-4057-8dcd-7b0f5e7be616.png)

**Comment by samuk** [comment]
Nice. Will check it out!

**Comment by samuk** [comment]
Maybe https://github.com/yorikvanhavre/WebTools too?

**Comment by mmiscool** [comment]
@samuk Here is a video showing how to import from FCStd 
https://youtu.be/VjoP9uSRSYs

It should work in the recently updated build running here.
https://autodrop.cloud/jsketcher/
