### ISSUE TITLE
feature request: Allow plane to be created relative to face with offset from face. 

### ISSUE THREAD

**Issue by mmiscool** [xibyte/jsketcher#17]
Workflow would be to select a face and then click the plane command. Plane would initialy be created on the face and allow the user to specify an offset distance positive or negative.

**Comment by mmiscool** [comment]
Would also be valuable for the plane to update if the face moves. 

In the plane creation dialog there would need to be a checkbox for linked plane or unlinked plane.

**Comment by xibyte** [comment]
Done. Now a face could be selected in the wizard as an alternative option.
