### ISSUE TITLE
UI: could you add a view cube?

### ISSUE THREAD

**Issue by MattFerraro** [xibyte/jsketcher#173]
most other CAD programs feature a convenient "view cube" in the upper right corner which rotates in sync with the primary camera. The cube has faces labeled like "top" "front" and "right" and if you click those faces, the main camera rotates to center that face. This is a very convenient shortcut and a familiar UI paradigm in other programs--could JSketcher provide it as well?

JSketcher currently features a set of axes in the lower right corner. That could go away in a future that features a view cube

**Comment by mmiscool** [comment]
Added in dev branch.
![ezgif-1-10fc30bbc2](https://user-images.githubusercontent.com/6439772/201513051-78eb2a10-70ee-4f9b-a33c-d74388d98ebe.gif)
