### ISSUE TITLE
Export as FCStd

### ISSUE THREAD

**Issue by samuk** [xibyte/jsketcher#179]
Would it be possible to support export in FCStd format as well as the import?

https://github.com/xibyte/jsketcher/issues/160#issuecomment-1198938774

**Comment by mmiscool** [comment]
We can do an export to brp. That is the OpenCASCADE internal format. FreeCAD opens those files with out any resistance. A FCStd file is just a zip file containing some XML and a collection of brp files. 

Would brp export fit your use case or do you absolutely need FCStd output?

**Comment by samuk** [comment]
Yes it sounds like brp would do the job. Thanks

**Comment by mmiscool** [comment]
Ok. I think we can get this working relatively soon. Stay tuned for when this will drop.

**Comment by samuk** [comment]
Actually thinking about this, proper FCStd would be preferable. I'm thinking of future integration with Github/Gitlab where you could load your FCStd from a git URL and then save your changes to Git.

Does that seem at all viable/on your roadmap?

**Comment by mmiscool** [comment]
Import / export functionality relating directly to FCStd is really only for single direction data migration. It would not be especially good for active community design as each time a model is loaded or stored only the geometry is preserved. The part history would not be preserved going from one CAD application to another.

**Comment by samuk** [comment]
Is it possible to record the part history in a FCStd? I realise it's probably low-priority work. I do think frictionless compatibility with FreeCAD would aid adoption and resolve some use cases where FreeCAD currently has more functionality.

Put another way: If Jsketcher fulfils 90% of my design needs I'm likely to use it, and do finishing work in Freecad.

If I can't do finishing work in Freecad, then I'd probably have to use it for the whold project from start to finish.

**Comment by mmiscool** [comment]
Well for now I pushed the "Export BREP" command. 
If you run from the dev branch you can give it a try.

**Comment by mmiscool** [comment]
@samuk Was the export brep adequate for loading models produced in JSketcher to FreeCAD?

**Comment by samuk** [comment]
To be completely honest I found working with FLOSS cad tools so frustrating, I've just started working in ways that don't require 3D modeling. I'll try again in a couple of years, but the learning curve was too steep.

**Comment by mmiscool** [comment]
Closing issue for now.
