### ISSUE TITLE
performing operation with current parameters leads to an invalid object (self-intersecting / zero-thickness / complete degeneration or unsupported cases)

### ISSUE THREAD

**Issue by oguzhannkayaa** [xibyte/jsketcher#199]
name:bug
during import the .dwg or emf format image. Which file format does it support? Because it is not written in anywhere

Also, how can I convert 3d view to 2d view app.

**Comment by mmiscool** [comment]
Hello,
Import of .dxf files works for basic entities like line work, arcs, points, circles, ellipse. 

I made a short video showing how to get in to the 2d sketcher and showing a dxf import.
https://youtu.be/_S8Bq3GKX04

I don't quite understand the title of your issue.

> performing operation with current parameters leads to an invalid object (self-intersecting / zero-thickness / complete degeneration or unsupported cases) 

Could you explain further the problem you are having?

**Comment by mmiscool** [comment]
Closing issue @oguzhannkayaa 
Go ahead and reopen the issue if needed. 

To use the 2d sketcher goto https://hostLcation/sketcher.html rather than https://hostLcation/index.html

Only DXF importing is supported at the moment. The proprietary DWG format is not supported.
