### ISSUE TITLE
Not an issue. But holly frigging cow. How can i send you money. 

### ISSUE THREAD

**Issue by mmiscool** [xibyte/jsketcher#2]
This is an amazing accomplishment. 

I am truly blown away by what you have been able to get done here.

please keep up the good work.

HAve you considered kick starting this?

**Comment by xibyte** [comment]
Thank you very much for your interest! I will definitely keep working on it and I have a lot of plans and ideas. One of those is to eventually implement the BREP models once I am done with the meshes.

I didn't really think about kick starting this yet but maybe I should.

**Comment by ShreyasWao** [comment]
I agree! This is really amazing stuff

**Comment by mmiscool** [comment]
Donate button added to main project page here on github.
