### ISSUE TITLE
Feature Request: Offset curve for 2d sketcher.

### ISSUE THREAD

**Issue by mmiscool** [xibyte/jsketcher#32]
It would be beneficial to be able to create an offset curve in the 2d sketcher. 

It would be desired to be able to select a series of curves and offset them by a specified distance such that modifying the original curve will also update the offset curve.

**Comment by xibyte** [comment]
checked my first approach to this feature. Some work is yet to be done.

**Comment by xibyte** [comment]
only works on closed loops for the time being. offset for arbitrary polylines can be done is different request.
