### ISSUE TITLE
BUG?: Deployment problem: ERROR in ./~/css-loader?-url!./~/less-loader!./web/css/app.less

### ISSUE THREAD

**Issue by cstewart000** [xibyte/jsketcher#41]
Mac OS V. 10.12.2
node: v0.10.36
on Chrome

Hi, I get a few errors after running the start command:

ERROR in ./~/css-loader?-url!./~/less-loader!./web/css/app.less
Module build failed: ReferenceError: Promise is not defined

[JSsketcher log.txt](https://github.com/xibyte/jsketcher/files/688790/JSsketcher.log.txt)

**Comment by idubrov** [comment]
Try updating your Node.js, v0.10.36 is way too old.
