### ISSUE TITLE
[Bug] Union 2 shells: side faces are in same plane, resulted a null shell

### ISSUE THREAD

**Issue by YuZhangGHub** [xibyte/jsketcher#47]
The code to reproduce: 

var mat = new Matrix3();
var m = mat.translate(0, 0, 10);

var box1 = brep_prim.box(100, 100, 100, undefined);
var box2 = brep_prim.box(100, 100, 100, mat);

var shell = boolean.union(box1, box2);

Then shell will have zero faces.

**Comment by xibyte** [comment]
confirm. Doesn't merge the adjacent overlapping surfaces right for the unioin operation.
