### ISSUE TITLE
STL file export broken 

### ISSUE THREAD

**Issue by mmiscool** [xibyte/jsketcher#50]
STL file export button produces no stl file.

Would also be nice if the stl file could be stored to local storage.

**Comment by ShaunHolt** [comment]
I noticed it does not work in Edge Browser, but does work fine in Chrome browser. Will test in other browsers later.

**Comment by AlbertoPa** [comment]
I confirm it works in Firefox but not in Edge.

**Comment by mmiscool** [comment]
Working as of latest
