### ISSUE TITLE
Bug: add package jwerty to packages install list

### ISSUE THREAD

**Issue by mmiscool** [xibyte/jsketcher#62]
jwerty package missing from install list.

npm install jwerty

**Comment by mmiscool** [comment]
This is no longer an issue as of latest version.

**Comment by RichardWhitfieldTTW** [comment]
Downloaded this morning and was having a play.  Had to load jwerty separately (everything else installed ok).  Seems to be ok in the package.json but didn't automatically install (Javascript noob here but if I figure it out I will let you know).

**Comment by xibyte** [comment]
@RichardWhitfieldTTW , you are right, the problem wasn't fixed for the 2d sketcher only for 3d. Just fixed it here https://github.com/xibyte/jsketcher/commit/f7867b36b2e007687d00c37d8cbb296dd4d0fb0a.
