### ISSUE TITLE
Bug: Error Module nurbs not found causing webpack to fail on start

### ISSUE THREAD

**Issue by brycehenley** [xibyte/jsketcher#65]
Error while trying to start app built from master branch.

ERROR in ./web/app/cad/sandbox.js
Module not found: Error: Can't resolve '../brep/geom/impl/nurbs' in '/storage/Code/OSC/jsketcher/web/app/cad'
 @ ./web/app/cad/sandbox.js 18:13-47
 @ ./web/app/cad/projectPlugin.js
 @ ./web/app/cad/init/startApplication.js
 @ ./web/app/index.js
 @ multi babel-polyfill ./web/app/index
webpack: Failed to compile.

**Comment by chromecity** [comment]
Is there a work-around for this?  I'd like to use jsketcher, but this happens on every attempt to start it, so I cannot.

**Comment by mmiscool** [comment]
Issue not present in current master.
