### ISSUE TITLE
Incorrect cut result

### ISSUE THREAD

**Issue by sphui** [xibyte/jsketcher#66]
I firstly cut through a box to box1 and box2, then cut box1 not fully through it, but in the result box2 disappeared.
<img width="1079" alt="2018-05-14 11 34 32" src="https://user-images.githubusercontent.com/1787424/39977311-b024b262-576b-11e8-9674-bc9268c3eebb.png">
<img width="1044" alt="2018-05-14 11 35 52" src="https://user-images.githubusercontent.com/1787424/39977316-b9595c48-576b-11e8-83c0-aa95b9e48246.png">

Below is the unit test dumped from the debug tool:

{"name":"DEFAULT","state":{"sketches":{"1:5":{"Segment":[[[1679.0000000030768,476.0000000002789],[1679.0000000030768,1130.0000000002738]],[[674.0000000031407,476.0000000002789],[1679.0000000030768,476.0000000002789]],[[674.0000000031407,1130.0000000002738],[674.0000000031407,476.0000000002789]],[[1679.0000000030768,1130.0000000002738],[674.0000000031407,1130.0000000002738]]]},"1:3":{"Segment":[[[53.44686111157002,1330.000000035616],[232.62237486919534,1330.000000035615]],[[232.62237486919534,1330.000000035615],[232.62237486919534,275.99999999741334]],[[232.62237486919534,275.99999999741334],[53.44686111156998,276.0000003009777]],[[53.44686111156998,276.0000003009777],[53.44686111157002,1330.000000035616]]]},"0:0":{"Segment":[[[474,1330],[1879,1330]],[[1879,1330],[1879,276]],[[1879,276],[474,276]],[[474,276],[474,1330]]]}},"operations":[{"type":"PLANE","params":{"orientation":"XY","parallelTo":"","depth":0}},{"type":"EXTRUDE","params":{"value":300,"prism":1,"angle":0,"rotation":0,"face":"0:0"}},{"type":"CUT","params":{"value":1500,"prism":1,"angle":0,"rotation":0,"face":"1:3"}},{"type":"CUT","params":{"value":150,"prism":1,"angle":0,"rotation":0,"face":"1:5"}}]},"expected":{"format":"LOOPS","vertices":[[474,275.99999999741334,232.62237486919534],[474,276,300],[474,1330,300],[474,1330.000000035615,232.62237486919534],[674.0000000031407,476.0000000002789,232.62237486919534],[674.0000000031407,476.0000000002789,300],[674.0000000031407,1130.0000000002738,232.62237486919537],[674.0000000031407,1130.0000000002738,300],[1679.0000000030768,476.0000000002789,232.6223748691953],[1679.0000000030768,476.0000000002789,300],[1679.0000000030768,1130.0000000002738,232.62237486919537],[1679.0000000030768,1130.0000000002738,300],[1878.9999999999998,276,232.6223748691953],[1879,276,300],[1879,1330,300],[1879,1330.000000035615,232.62237486919534]],"faces":[[[13,12,15,14]],[[3,15,12,0],[4,8,10,6]],[[14,15,3,2]],[[1,0,12,13]],[[2,3,0,1]],[[10,8,9,11]],[[6,10,11,7]],[[4,6,7,5]],[[8,4,5,9]],[[1,13,14,2],[7,11,9,5]]]}}

**Comment by mmiscool** [comment]
![image](https://user-images.githubusercontent.com/6439772/77507328-9ed4df00-6e3e-11ea-969f-12d8c836cd41.png)
This is no longer an issue in the current master. Multi body solids do not break at this time.
