### ISSUE TITLE
Import DXF file from local

### ISSUE THREAD

**Issue by StevenKung** [xibyte/jsketcher#67]
Hi xibyte and mmiscool

This app is awesome!
I have a question about how can I import the DXF file from local?
thanks

**Comment by xibyte** [comment]
There is no way currently. However it is a nice feature to have and it's definitely on my list of things to implement. Thanks for the suggestion I can start working on it as soon as I am done with the 3d brep engine.

**Comment by TheMBeat** [comment]
Hey xibyte and mmiscool,

how about the feature? 

thanks

**Comment by mmiscool** [comment]
On the radar but not at top of priority list.

**Comment by mmiscool** [comment]
Basic DXF import functionality implemented. 
![Screenshot 2022-12-04 11 56 11 PM](https://user-images.githubusercontent.com/6439772/205552895-56a1ac61-c91a-4d78-aabd-40771692746f.png)

**Comment by jtcheng** [comment]
@mmiscool 
There're two issues for import with dxf file:
1. the rectangle elements are loss.
2. no constraint is created (detect) from the import dxf file, we need to manually create all the constraint, this is not easy for large dxf.

**Comment by mmiscool** [comment]
@jtcheng Try the latest dev branch. It should be working now.
