### ISSUE TITLE
Sketch: no apparent way to delete green visual dimensions

### ISSUE THREAD

**Issue by z26** [xibyte/jsketcher#70]

**Comment by mmiscool** [comment]
Partially fixed at this point. Linear dimensions are selectable and can be deleted after creation. 
![test-_6_](https://user-images.githubusercontent.com/6439772/77727297-59e0b200-6fd0-11ea-9f5a-561662eb4426.gif)

**Comment by mmiscool** [comment]
Radius now supports moving its location and deletion.
