### ISSUE TITLE
Bezier curve - resolution not transfer

### ISSUE THREAD

**Issue by fcollonval** [xibyte/jsketcher#72]
Dear developer, 

I think there is a bug there. The resolution is not transfer to Bezier curve constructor. 

https://github.com/xibyte/jsketcher/blob/6a89859da55aa6f0f568f2dea5ca395786e9c370/web/app/cad/sketch/sketchModel.js#L139

**Comment by mmiscool** [comment]
The sketcher code has been refactored since this issue was created. 
Closing issue.
