### ISSUE TITLE
jsketcher does not start

### ISSUE THREAD

**Issue by ssmns** [xibyte/jsketcher#81]
"npm start"  failed : 
**> jsketcher@0.1.0 start /home/ssmns/Downloads/NodeJs/jsketcher-master
> node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --config webpack.config.js --content-base web/ --port 3000 --host 0.0.0.0

ℹ ｢wds｣: Project is running at http://0.0.0.0:3000/webpack-dev-server/
ℹ ｢wds｣: webpack output is served from /static/
ℹ ｢wds｣: Content not from webpack is served from /home/ssmns/Downloads/NodeJs/jsketcher-master/web
✖ ｢wdm｣: Hash: fed2571555d9a69aa5ed
Version: webpack 4.26.1
Time: 13000ms
Built at: 2019-02-10 14:59:47
                 Asset      Size    Chunks             Chunk Names
       index.bundle.js  5.02 MiB     index  [emitted]  index
   index.bundle.js.map  5.38 MiB     index  [emitted]  index
    sketcher.bundle.js  1.57 MiB  sketcher  [emitted]  sketcher
sketcher.bundle.js.map  1.85 MiB  sketcher  [emitted]  sketcher
Entrypoint index = index.bundle.js index.bundle.js.map
Entrypoint sketcher = sketcher.bundle.js sketcher.bundle.js.map
[0] multi babel-polyfill ./web/app/index 40 bytes {index} [built]
[1] multi babel-polyfill ./web/app/sketcher 40 bytes {sketcher} [built]
[./node_modules/babel-polyfill/lib/index.js] 833 bytes {index} {sketcher} [built]
[./node_modules/babel-polyfill/node_modules/core-js/fn/regexp/escape.js] 108 bytes {index} {sketcher} [built]
[./node_modules/babel-polyfill/node_modules/core-js/shim.js] 7.99 KiB {index} {sketcher} [built]
[./node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js] 23.9 KiB {index} {sketcher} [built]
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {index} {sketcher} [built]
[./web/app/cad/init/startApplication.js] 4.6 KiB {index} [built]
[./web/app/index.js] 131 bytes {index} [built]
[./web/app/sketcher.js] 10.4 KiB {sketcher} [built]
[./web/app/sketcher/parametric.js] 54.1 KiB {index} {sketcher} [built]
[./web/app/sketcher/sketcher-app.js] 14.8 KiB {sketcher} [built]
[./web/app/sketcher/styles.js] 746 bytes {index} {sketcher} [built]
[./web/app/sketcher/viewer2d.js] 18.2 KiB {index} {sketcher} [built]
[./web/app/ui/toolkit.js] 9.35 KiB {index} {sketcher} [built]
    + 843 hidden modules

ERROR in ./web/app/cad/craft/spatialCurve/spatialCurveOperation.js
Module not found: Error: Can't resolve './SpatialCurveOpSchema' in '/home/ssmns/Downloads/NodeJs/jsketcher-master/web/app/cad/craft/spatialCurve'
 @ ./web/app/cad/craft/spatialCurve/spatialCurveOperation.js 5:0-58
 @ ./web/app/cad/part/partOperationsPlugin.js
 @ ./web/app/cad/part/partModelerPlugins.js
 @ ./web/app/cad/init/startApplication.js
 @ ./web/app/index.js
 @ multi babel-polyfill ./web/app/index
ℹ ｢wdm｣: Failed to compile.**

**Comment by mmiscool** [comment]
Current master version should build with out issue.
