### ISSUE TITLE
Feature Request - 2D Sketcher

### ISSUE THREAD

**Issue by tlcoder** [xibyte/jsketcher#83]
Can you make it so you can click or double click on a dimension which would allow you to edit it and update the drawing?

http://web-cad.org/sketcher.html#__sample2D__

Thanks

**Comment by mmiscool** [comment]
This is on the list. There are some significant changes happening in the 2d sketcher including graphical representation of constraints.

**Comment by mmiscool** [comment]
Wooooooooot. This one is now working. Double click to edit dimensions.
