### ISSUE TITLE
sample files

### ISSUE THREAD

**Issue by ThorsenRune** [xibyte/jsketcher#93]
Hi, this project looks great. May I propose to put some (five) sample models that can be loaded for visitors to play with. ( Im looking for an alternative to Onshape for open codesing projects)

**Comment by mmiscool** [comment]
@ThorsenRune  Do you possibly have some particular mechanical drafting examples that you would like to see? Preferably old text book exercises that might be in the public domain.

Examples like that would assist in making test cases for the automated test frame work.

**Comment by ThorsenRune** [comment]
As I think this project could be great for solving the co-design issue of affordable 3D design I tried it out. Unfortunately I was stuck in not knowing how to edit a sketch as the workflow seems different from what I know. I was looking for help allover but did not find any. 
As for examples  can I send you a private message and how?

**Comment by mmiscool** [comment]
The current version has 3d sketching broken at the moment. You can get in to the fallback 2d sketcher.

The normal process to start building a part is to add a plane the the model. Select the plane and click the sketch icon.

In the top right hand corner of the graphics area you should see a tool bar with 3 buttons. If you click the center button it will open up the sketcher tool in 2d mode. 

Once you are done with the sketch in the 2d mode you should click the save button and exit out of the 2d sketch tab located at the bottom of the screen. I will make a little graphic to show this. 
![ezgif-6-3ce96fbe05aa](https://user-images.githubusercontent.com/6439772/77990555-a3424180-72ef-11ea-970b-b80e9a2e4d8b.gif)

**Comment by ThorsenRune** [comment]
Hi mmiscool, thanks for your answer. I havent got so far learning the program yet so I dont know what you intend by 3d sketching. Great with the animation. Unfortunately Im on a laptop so its hard to see and I havent even got to the extrusion point yet. 
I have made a 1 page document about my initial experience if it can be helpful to understand users expectations. https://docs.google.com/document/d/1PGW2oKL6YULiER7IGxOojSPa7gDWvxKFMCluyaJr_bg/edit

**Comment by mmiscool** [comment]
looks like you have permissions turned on for that doc
