### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by ThorsenRune** [xibyte/jsketcher#95]

**Comment by mmiscool** [comment]
Yes it is.

**Comment by ThorsenRune** [comment]
Cool, it seems like a really nice and unique project.
 Are there a kind of users manual somewhere.
see also https://github.com/xibyte/jsketcher/issues/93

**Comment by mmiscool** [comment]
Help files are coming. 

The UI is stabilizing right now. More docks will be produced as the UI firms up.
